package mybatis.mapper;

import java.util.List;
import mybatis.model.Actor;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface ActorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.actor
     *
     * @mbg.generated
     */
    @Delete({
        "delete from public.actor",
        "where actor_id = #{actorId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer actorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.actor
     *
     * @mbg.generated
     */
    @Insert({
        "insert into public.actor (actor_id, first_name, ",
        "last_name, last_update)",
        "values (#{actorId,jdbcType=INTEGER}, #{firstName,jdbcType=VARCHAR}, ",
        "#{lastName,jdbcType=VARCHAR}, #{lastUpdate,jdbcType=TIMESTAMP})"
    })
    int insert(Actor row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.actor
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "actor_id, first_name, last_name, last_update",
        "from public.actor",
        "where actor_id = #{actorId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="actor_id", property="actorId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="first_name", property="firstName", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_name", property="lastName", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_update", property="lastUpdate", jdbcType=JdbcType.TIMESTAMP)
    })
    Actor selectByPrimaryKey(Integer actorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.actor
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "actor_id, first_name, last_name, last_update",
        "from public.actor"
    })
    @Results({
        @Result(column="actor_id", property="actorId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="first_name", property="firstName", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_name", property="lastName", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_update", property="lastUpdate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Actor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.actor
     *
     * @mbg.generated
     */
    @Update({
        "update public.actor",
        "set first_name = #{firstName,jdbcType=VARCHAR},",
          "last_name = #{lastName,jdbcType=VARCHAR},",
          "last_update = #{lastUpdate,jdbcType=TIMESTAMP}",
        "where actor_id = #{actorId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Actor row);
}