package mybatis.mapper;

import java.util.List;
import mybatis.model.City;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface CityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.city
     *
     * @mbg.generated
     */
    @Delete({
        "delete from public.city",
        "where city_id = #{cityId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.city
     *
     * @mbg.generated
     */
    @Insert({
        "insert into public.city (city_id, city, ",
        "country_id, last_update)",
        "values (#{cityId,jdbcType=INTEGER}, #{city,jdbcType=VARCHAR}, ",
        "#{countryId,jdbcType=SMALLINT}, #{lastUpdate,jdbcType=TIMESTAMP})"
    })
    int insert(City row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.city
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "city_id, city, country_id, last_update",
        "from public.city",
        "where city_id = #{cityId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="city_id", property="cityId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="city", property="city", jdbcType=JdbcType.VARCHAR),
        @Result(column="country_id", property="countryId", jdbcType=JdbcType.SMALLINT),
        @Result(column="last_update", property="lastUpdate", jdbcType=JdbcType.TIMESTAMP)
    })
    City selectByPrimaryKey(Integer cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.city
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "city_id, city, country_id, last_update",
        "from public.city"
    })
    @Results({
        @Result(column="city_id", property="cityId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="city", property="city", jdbcType=JdbcType.VARCHAR),
        @Result(column="country_id", property="countryId", jdbcType=JdbcType.SMALLINT),
        @Result(column="last_update", property="lastUpdate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<City> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.city
     *
     * @mbg.generated
     */
    @Update({
        "update public.city",
        "set city = #{city,jdbcType=VARCHAR},",
          "country_id = #{countryId,jdbcType=SMALLINT},",
          "last_update = #{lastUpdate,jdbcType=TIMESTAMP}",
        "where city_id = #{cityId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(City row);
}