package mybatis.mapper;

import java.util.List;
import mybatis.model.Country;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface CountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.country
     *
     * @mbg.generated
     */
    @Delete({
        "delete from public.country",
        "where country_id = #{countryId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer countryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.country
     *
     * @mbg.generated
     */
    @Insert({
        "insert into public.country (country_id, country, ",
        "last_update)",
        "values (#{countryId,jdbcType=INTEGER}, #{country,jdbcType=VARCHAR}, ",
        "#{lastUpdate,jdbcType=TIMESTAMP})"
    })
    int insert(Country row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.country
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "country_id, country, last_update",
        "from public.country",
        "where country_id = #{countryId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="country_id", property="countryId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="country", property="country", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_update", property="lastUpdate", jdbcType=JdbcType.TIMESTAMP)
    })
    Country selectByPrimaryKey(Integer countryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.country
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "country_id, country, last_update",
        "from public.country"
    })
    @Results({
        @Result(column="country_id", property="countryId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="country", property="country", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_update", property="lastUpdate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Country> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.country
     *
     * @mbg.generated
     */
    @Update({
        "update public.country",
        "set country = #{country,jdbcType=VARCHAR},",
          "last_update = #{lastUpdate,jdbcType=TIMESTAMP}",
        "where country_id = #{countryId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Country row);
}