package mybatis.mapper;

import java.util.List;
import mybatis.model.Customer;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.customer
     *
     * @mbg.generated
     */
    @Delete({
        "delete from public.customer",
        "where customer_id = #{customerId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.customer
     *
     * @mbg.generated
     */
    @Insert({
        "insert into public.customer (customer_id, store_id, ",
        "first_name, last_name, ",
        "email, address_id, ",
        "activebool, create_date, ",
        "last_update, active)",
        "values (#{customerId,jdbcType=INTEGER}, #{storeId,jdbcType=SMALLINT}, ",
        "#{firstName,jdbcType=VARCHAR}, #{lastName,jdbcType=VARCHAR}, ",
        "#{email,jdbcType=VARCHAR}, #{addressId,jdbcType=SMALLINT}, ",
        "#{activebool,jdbcType=BIT}, #{createDate,jdbcType=DATE}, ",
        "#{lastUpdate,jdbcType=TIMESTAMP}, #{active,jdbcType=INTEGER})"
    })
    int insert(Customer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.customer
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "customer_id, store_id, first_name, last_name, email, address_id, activebool, ",
        "create_date, last_update, active",
        "from public.customer",
        "where customer_id = #{customerId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="customer_id", property="customerId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="store_id", property="storeId", jdbcType=JdbcType.SMALLINT),
        @Result(column="first_name", property="firstName", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_name", property="lastName", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="address_id", property="addressId", jdbcType=JdbcType.SMALLINT),
        @Result(column="activebool", property="activebool", jdbcType=JdbcType.BIT),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.DATE),
        @Result(column="last_update", property="lastUpdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="active", property="active", jdbcType=JdbcType.INTEGER)
    })
    Customer selectByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.customer
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "customer_id, store_id, first_name, last_name, email, address_id, activebool, ",
        "create_date, last_update, active",
        "from public.customer"
    })
    @Results({
        @Result(column="customer_id", property="customerId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="store_id", property="storeId", jdbcType=JdbcType.SMALLINT),
        @Result(column="first_name", property="firstName", jdbcType=JdbcType.VARCHAR),
        @Result(column="last_name", property="lastName", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="address_id", property="addressId", jdbcType=JdbcType.SMALLINT),
        @Result(column="activebool", property="activebool", jdbcType=JdbcType.BIT),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.DATE),
        @Result(column="last_update", property="lastUpdate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="active", property="active", jdbcType=JdbcType.INTEGER)
    })
    List<Customer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.customer
     *
     * @mbg.generated
     */
    @Update({
        "update public.customer",
        "set store_id = #{storeId,jdbcType=SMALLINT},",
          "first_name = #{firstName,jdbcType=VARCHAR},",
          "last_name = #{lastName,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "address_id = #{addressId,jdbcType=SMALLINT},",
          "activebool = #{activebool,jdbcType=BIT},",
          "create_date = #{createDate,jdbcType=DATE},",
          "last_update = #{lastUpdate,jdbcType=TIMESTAMP},",
          "active = #{active,jdbcType=INTEGER}",
        "where customer_id = #{customerId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Customer row);
}