package mybatis.mapper;

import java.util.List;
import mybatis.model.FilmActor;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface FilmActorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film_actor
     *
     * @mbg.generated
     */
    @Delete({
        "delete from public.film_actor",
        "where actor_id = #{actorId,jdbcType=SMALLINT}",
          "and film_id = #{filmId,jdbcType=SMALLINT}"
    })
    int deleteByPrimaryKey(@Param("actorId") Short actorId, @Param("filmId") Short filmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film_actor
     *
     * @mbg.generated
     */
    @Insert({
        "insert into public.film_actor (actor_id, film_id, ",
        "last_update)",
        "values (#{actorId,jdbcType=SMALLINT}, #{filmId,jdbcType=SMALLINT}, ",
        "#{lastUpdate,jdbcType=TIMESTAMP})"
    })
    int insert(FilmActor row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film_actor
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "actor_id, film_id, last_update",
        "from public.film_actor",
        "where actor_id = #{actorId,jdbcType=SMALLINT}",
          "and film_id = #{filmId,jdbcType=SMALLINT}"
    })
    @Results({
        @Result(column="actor_id", property="actorId", jdbcType=JdbcType.SMALLINT, id=true),
        @Result(column="film_id", property="filmId", jdbcType=JdbcType.SMALLINT, id=true),
        @Result(column="last_update", property="lastUpdate", jdbcType=JdbcType.TIMESTAMP)
    })
    FilmActor selectByPrimaryKey(@Param("actorId") Short actorId, @Param("filmId") Short filmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film_actor
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "actor_id, film_id, last_update",
        "from public.film_actor"
    })
    @Results({
        @Result(column="actor_id", property="actorId", jdbcType=JdbcType.SMALLINT, id=true),
        @Result(column="film_id", property="filmId", jdbcType=JdbcType.SMALLINT, id=true),
        @Result(column="last_update", property="lastUpdate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<FilmActor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film_actor
     *
     * @mbg.generated
     */
    @Update({
        "update public.film_actor",
        "set last_update = #{lastUpdate,jdbcType=TIMESTAMP}",
        "where actor_id = #{actorId,jdbcType=SMALLINT}",
          "and film_id = #{filmId,jdbcType=SMALLINT}"
    })
    int updateByPrimaryKey(FilmActor row);
}