package mybatis.mapper;

import java.util.List;
import mybatis.model.FilmCategory;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface FilmCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film_category
     *
     * @mbg.generated
     */
    @Delete({
        "delete from public.film_category",
        "where film_id = #{filmId,jdbcType=SMALLINT}",
          "and category_id = #{categoryId,jdbcType=SMALLINT}"
    })
    int deleteByPrimaryKey(@Param("filmId") Short filmId, @Param("categoryId") Short categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film_category
     *
     * @mbg.generated
     */
    @Insert({
        "insert into public.film_category (film_id, category_id, ",
        "last_update)",
        "values (#{filmId,jdbcType=SMALLINT}, #{categoryId,jdbcType=SMALLINT}, ",
        "#{lastUpdate,jdbcType=TIMESTAMP})"
    })
    int insert(FilmCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film_category
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "film_id, category_id, last_update",
        "from public.film_category",
        "where film_id = #{filmId,jdbcType=SMALLINT}",
          "and category_id = #{categoryId,jdbcType=SMALLINT}"
    })
    @Results({
        @Result(column="film_id", property="filmId", jdbcType=JdbcType.SMALLINT, id=true),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.SMALLINT, id=true),
        @Result(column="last_update", property="lastUpdate", jdbcType=JdbcType.TIMESTAMP)
    })
    FilmCategory selectByPrimaryKey(@Param("filmId") Short filmId, @Param("categoryId") Short categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film_category
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "film_id, category_id, last_update",
        "from public.film_category"
    })
    @Results({
        @Result(column="film_id", property="filmId", jdbcType=JdbcType.SMALLINT, id=true),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.SMALLINT, id=true),
        @Result(column="last_update", property="lastUpdate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<FilmCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film_category
     *
     * @mbg.generated
     */
    @Update({
        "update public.film_category",
        "set last_update = #{lastUpdate,jdbcType=TIMESTAMP}",
        "where film_id = #{filmId,jdbcType=SMALLINT}",
          "and category_id = #{categoryId,jdbcType=SMALLINT}"
    })
    int updateByPrimaryKey(FilmCategory row);
}