package mybatis.mapper;

import java.util.List;
import mybatis.model.Inventory;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface InventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inventory
     *
     * @mbg.generated
     */
    @Delete({
        "delete from public.inventory",
        "where inventory_id = #{inventoryId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer inventoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inventory
     *
     * @mbg.generated
     */
    @Insert({
        "insert into public.inventory (inventory_id, film_id, ",
        "store_id, last_update)",
        "values (#{inventoryId,jdbcType=INTEGER}, #{filmId,jdbcType=SMALLINT}, ",
        "#{storeId,jdbcType=SMALLINT}, #{lastUpdate,jdbcType=TIMESTAMP})"
    })
    int insert(Inventory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inventory
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "inventory_id, film_id, store_id, last_update",
        "from public.inventory",
        "where inventory_id = #{inventoryId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="inventory_id", property="inventoryId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="film_id", property="filmId", jdbcType=JdbcType.SMALLINT),
        @Result(column="store_id", property="storeId", jdbcType=JdbcType.SMALLINT),
        @Result(column="last_update", property="lastUpdate", jdbcType=JdbcType.TIMESTAMP)
    })
    Inventory selectByPrimaryKey(Integer inventoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inventory
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "inventory_id, film_id, store_id, last_update",
        "from public.inventory"
    })
    @Results({
        @Result(column="inventory_id", property="inventoryId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="film_id", property="filmId", jdbcType=JdbcType.SMALLINT),
        @Result(column="store_id", property="storeId", jdbcType=JdbcType.SMALLINT),
        @Result(column="last_update", property="lastUpdate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Inventory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inventory
     *
     * @mbg.generated
     */
    @Update({
        "update public.inventory",
        "set film_id = #{filmId,jdbcType=SMALLINT},",
          "store_id = #{storeId,jdbcType=SMALLINT},",
          "last_update = #{lastUpdate,jdbcType=TIMESTAMP}",
        "where inventory_id = #{inventoryId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Inventory row);
}