package mybatis.mapper;

import java.util.List;
import mybatis.model.NicerButSlowerFilmList;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface NicerButSlowerFilmListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.nicer_but_slower_film_list
     *
     * @mbg.generated
     */
    @Insert({
        "insert into public.nicer_but_slower_film_list (fid, title, ",
        "description, category, ",
        "price, length, ",
        "rating, actors)",
        "values (#{fid,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{category,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=NUMERIC}, #{length,jdbcType=SMALLINT}, ",
        "#{rating,jdbcType=VARCHAR}, #{actors,jdbcType=VARCHAR})"
    })
    int insert(NicerButSlowerFilmList row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.nicer_but_slower_film_list
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "fid, title, description, category, price, length, rating, actors",
        "from public.nicer_but_slower_film_list"
    })
    @Results({
        @Result(column="fid", property="fid", jdbcType=JdbcType.INTEGER),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="category", property="category", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.NUMERIC),
        @Result(column="length", property="length", jdbcType=JdbcType.SMALLINT),
        @Result(column="rating", property="rating", jdbcType=JdbcType.VARCHAR),
        @Result(column="actors", property="actors", jdbcType=JdbcType.VARCHAR)
    })
    List<NicerButSlowerFilmList> selectAll();
}