package mybatis.mapper;

import java.util.List;
import mybatis.model.Payment;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface PaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment
     *
     * @mbg.generated
     */
    @Delete({
        "delete from public.payment",
        "where payment_id = #{paymentId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer paymentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment
     *
     * @mbg.generated
     */
    @Insert({
        "insert into public.payment (payment_id, customer_id, ",
        "staff_id, rental_id, ",
        "amount, payment_date)",
        "values (#{paymentId,jdbcType=INTEGER}, #{customerId,jdbcType=SMALLINT}, ",
        "#{staffId,jdbcType=SMALLINT}, #{rentalId,jdbcType=INTEGER}, ",
        "#{amount,jdbcType=NUMERIC}, #{paymentDate,jdbcType=TIMESTAMP})"
    })
    int insert(Payment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "payment_id, customer_id, staff_id, rental_id, amount, payment_date",
        "from public.payment",
        "where payment_id = #{paymentId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="payment_id", property="paymentId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="customer_id", property="customerId", jdbcType=JdbcType.SMALLINT),
        @Result(column="staff_id", property="staffId", jdbcType=JdbcType.SMALLINT),
        @Result(column="rental_id", property="rentalId", jdbcType=JdbcType.INTEGER),
        @Result(column="amount", property="amount", jdbcType=JdbcType.NUMERIC),
        @Result(column="payment_date", property="paymentDate", jdbcType=JdbcType.TIMESTAMP)
    })
    Payment selectByPrimaryKey(Integer paymentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "payment_id, customer_id, staff_id, rental_id, amount, payment_date",
        "from public.payment"
    })
    @Results({
        @Result(column="payment_id", property="paymentId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="customer_id", property="customerId", jdbcType=JdbcType.SMALLINT),
        @Result(column="staff_id", property="staffId", jdbcType=JdbcType.SMALLINT),
        @Result(column="rental_id", property="rentalId", jdbcType=JdbcType.INTEGER),
        @Result(column="amount", property="amount", jdbcType=JdbcType.NUMERIC),
        @Result(column="payment_date", property="paymentDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Payment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment
     *
     * @mbg.generated
     */
    @Update({
        "update public.payment",
        "set customer_id = #{customerId,jdbcType=SMALLINT},",
          "staff_id = #{staffId,jdbcType=SMALLINT},",
          "rental_id = #{rentalId,jdbcType=INTEGER},",
          "amount = #{amount,jdbcType=NUMERIC},",
          "payment_date = #{paymentDate,jdbcType=TIMESTAMP}",
        "where payment_id = #{paymentId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Payment row);
}