package mybatis.mapper;

import java.util.List;
import mybatis.model.Rental;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface RentalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rental
     *
     * @mbg.generated
     */
    @Delete({
        "delete from public.rental",
        "where rental_id = #{rentalId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer rentalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rental
     *
     * @mbg.generated
     */
    @Insert({
        "insert into public.rental (rental_id, rental_date, ",
        "inventory_id, customer_id, ",
        "return_date, staff_id, ",
        "last_update)",
        "values (#{rentalId,jdbcType=INTEGER}, #{rentalDate,jdbcType=TIMESTAMP}, ",
        "#{inventoryId,jdbcType=INTEGER}, #{customerId,jdbcType=SMALLINT}, ",
        "#{returnDate,jdbcType=TIMESTAMP}, #{staffId,jdbcType=SMALLINT}, ",
        "#{lastUpdate,jdbcType=TIMESTAMP})"
    })
    int insert(Rental row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rental
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "rental_id, rental_date, inventory_id, customer_id, return_date, staff_id, last_update",
        "from public.rental",
        "where rental_id = #{rentalId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="rental_id", property="rentalId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="rental_date", property="rentalDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="inventory_id", property="inventoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="customer_id", property="customerId", jdbcType=JdbcType.SMALLINT),
        @Result(column="return_date", property="returnDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="staff_id", property="staffId", jdbcType=JdbcType.SMALLINT),
        @Result(column="last_update", property="lastUpdate", jdbcType=JdbcType.TIMESTAMP)
    })
    Rental selectByPrimaryKey(Integer rentalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rental
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "rental_id, rental_date, inventory_id, customer_id, return_date, staff_id, last_update",
        "from public.rental"
    })
    @Results({
        @Result(column="rental_id", property="rentalId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="rental_date", property="rentalDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="inventory_id", property="inventoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="customer_id", property="customerId", jdbcType=JdbcType.SMALLINT),
        @Result(column="return_date", property="returnDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="staff_id", property="staffId", jdbcType=JdbcType.SMALLINT),
        @Result(column="last_update", property="lastUpdate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Rental> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rental
     *
     * @mbg.generated
     */
    @Update({
        "update public.rental",
        "set rental_date = #{rentalDate,jdbcType=TIMESTAMP},",
          "inventory_id = #{inventoryId,jdbcType=INTEGER},",
          "customer_id = #{customerId,jdbcType=SMALLINT},",
          "return_date = #{returnDate,jdbcType=TIMESTAMP},",
          "staff_id = #{staffId,jdbcType=SMALLINT},",
          "last_update = #{lastUpdate,jdbcType=TIMESTAMP}",
        "where rental_id = #{rentalId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Rental row);
}