package mybatis.mapper;

import java.util.List;
import mybatis.model.SalesByStore;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface SalesByStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.sales_by_store
     *
     * @mbg.generated
     */
    @Insert({
        "insert into public.sales_by_store (store, manager, ",
        "total_sales)",
        "values (#{store,jdbcType=VARCHAR}, #{manager,jdbcType=VARCHAR}, ",
        "#{totalSales,jdbcType=NUMERIC})"
    })
    int insert(SalesByStore row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.sales_by_store
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "store, manager, total_sales",
        "from public.sales_by_store"
    })
    @Results({
        @Result(column="store", property="store", jdbcType=JdbcType.VARCHAR),
        @Result(column="manager", property="manager", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_sales", property="totalSales", jdbcType=JdbcType.NUMERIC)
    })
    List<SalesByStore> selectAll();
}