package mybatis.mapper;

import java.util.List;
import mybatis.model.SalesByFilmCategory;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface SalesByFilmCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.sales_by_film_category
     *
     * @mbg.generated
     */
    @Insert({
        "insert into public.sales_by_film_category (category, total_sales)",
        "values (#{category,jdbcType=VARCHAR}, #{totalSales,jdbcType=NUMERIC})"
    })
    int insert(SalesByFilmCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.sales_by_film_category
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "category, total_sales",
        "from public.sales_by_film_category"
    })
    @Results({
        @Result(column="category", property="category", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_sales", property="totalSales", jdbcType=JdbcType.NUMERIC)
    })
    List<SalesByFilmCategory> selectAll();
}