package mybatis.mapper;

import java.util.List;
import mybatis.model.StaffList;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface StaffListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.staff_list
     *
     * @mbg.generated
     */
    @Insert({
        "insert into public.staff_list (id, name, ",
        "address, \"zip code\", ",
        "phone, city, country, ",
        "sid)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR}, #{zipCode,jdbcType=VARCHAR}, ",
        "#{phone,jdbcType=VARCHAR}, #{city,jdbcType=VARCHAR}, #{country,jdbcType=VARCHAR}, ",
        "#{sid,jdbcType=SMALLINT})"
    })
    int insert(StaffList row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.staff_list
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, address, \"zip code\", phone, city, country, sid",
        "from public.staff_list"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="zip code", property="zipCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="city", property="city", jdbcType=JdbcType.VARCHAR),
        @Result(column="country", property="country", jdbcType=JdbcType.VARCHAR),
        @Result(column="sid", property="sid", jdbcType=JdbcType.SMALLINT)
    })
    List<StaffList> selectAll();
}