package mybatis.mapper;

import java.util.List;
import mybatis.model.Store;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface StoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.store
     *
     * @mbg.generated
     */
    @Delete({
        "delete from public.store",
        "where store_id = #{storeId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer storeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.store
     *
     * @mbg.generated
     */
    @Insert({
        "insert into public.store (store_id, manager_staff_id, ",
        "address_id, last_update)",
        "values (#{storeId,jdbcType=INTEGER}, #{managerStaffId,jdbcType=SMALLINT}, ",
        "#{addressId,jdbcType=SMALLINT}, #{lastUpdate,jdbcType=TIMESTAMP})"
    })
    int insert(Store row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.store
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "store_id, manager_staff_id, address_id, last_update",
        "from public.store",
        "where store_id = #{storeId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="store_id", property="storeId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="manager_staff_id", property="managerStaffId", jdbcType=JdbcType.SMALLINT),
        @Result(column="address_id", property="addressId", jdbcType=JdbcType.SMALLINT),
        @Result(column="last_update", property="lastUpdate", jdbcType=JdbcType.TIMESTAMP)
    })
    Store selectByPrimaryKey(Integer storeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.store
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "store_id, manager_staff_id, address_id, last_update",
        "from public.store"
    })
    @Results({
        @Result(column="store_id", property="storeId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="manager_staff_id", property="managerStaffId", jdbcType=JdbcType.SMALLINT),
        @Result(column="address_id", property="addressId", jdbcType=JdbcType.SMALLINT),
        @Result(column="last_update", property="lastUpdate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Store> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.store
     *
     * @mbg.generated
     */
    @Update({
        "update public.store",
        "set manager_staff_id = #{managerStaffId,jdbcType=SMALLINT},",
          "address_id = #{addressId,jdbcType=SMALLINT},",
          "last_update = #{lastUpdate,jdbcType=TIMESTAMP}",
        "where store_id = #{storeId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Store row);
}