package mybatis.model;

public class ActorInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.actor_info.actor_id
     *
     * @mbg.generated
     */
    private Integer actorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.actor_info.first_name
     *
     * @mbg.generated
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.actor_info.last_name
     *
     * @mbg.generated
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.actor_info.film_info
     *
     * @mbg.generated
     */
    private String filmInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.actor_info.actor_id
     *
     * @return the value of public.actor_info.actor_id
     *
     * @mbg.generated
     */
    public Integer getActorId() {
        return actorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.actor_info.actor_id
     *
     * @param actorId the value for public.actor_info.actor_id
     *
     * @mbg.generated
     */
    public void setActorId(Integer actorId) {
        this.actorId = actorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.actor_info.first_name
     *
     * @return the value of public.actor_info.first_name
     *
     * @mbg.generated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.actor_info.first_name
     *
     * @param firstName the value for public.actor_info.first_name
     *
     * @mbg.generated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.actor_info.last_name
     *
     * @return the value of public.actor_info.last_name
     *
     * @mbg.generated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.actor_info.last_name
     *
     * @param lastName the value for public.actor_info.last_name
     *
     * @mbg.generated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.actor_info.film_info
     *
     * @return the value of public.actor_info.film_info
     *
     * @mbg.generated
     */
    public String getFilmInfo() {
        return filmInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.actor_info.film_info
     *
     * @param filmInfo the value for public.actor_info.film_info
     *
     * @mbg.generated
     */
    public void setFilmInfo(String filmInfo) {
        this.filmInfo = filmInfo == null ? null : filmInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.actor_info
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ActorInfo other = (ActorInfo) that;
        return (this.getActorId() == null ? other.getActorId() == null : this.getActorId().equals(other.getActorId()))
            && (this.getFirstName() == null ? other.getFirstName() == null : this.getFirstName().equals(other.getFirstName()))
            && (this.getLastName() == null ? other.getLastName() == null : this.getLastName().equals(other.getLastName()))
            && (this.getFilmInfo() == null ? other.getFilmInfo() == null : this.getFilmInfo().equals(other.getFilmInfo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.actor_info
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getActorId() == null) ? 0 : getActorId().hashCode());
        result = prime * result + ((getFirstName() == null) ? 0 : getFirstName().hashCode());
        result = prime * result + ((getLastName() == null) ? 0 : getLastName().hashCode());
        result = prime * result + ((getFilmInfo() == null) ? 0 : getFilmInfo().hashCode());
        return result;
    }
}