package mybatis.model;

import java.time.LocalDate;
import java.time.LocalDateTime;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.customer_id
     *
     * @mbg.generated
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.store_id
     *
     * @mbg.generated
     */
    private Short storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.first_name
     *
     * @mbg.generated
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.last_name
     *
     * @mbg.generated
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.address_id
     *
     * @mbg.generated
     */
    private Short addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.activebool
     *
     * @mbg.generated
     */
    private Boolean activebool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.create_date
     *
     * @mbg.generated
     */
    private LocalDate createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.last_update
     *
     * @mbg.generated
     */
    private LocalDateTime lastUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.active
     *
     * @mbg.generated
     */
    private Integer active;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.customer_id
     *
     * @return the value of public.customer.customer_id
     *
     * @mbg.generated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.customer_id
     *
     * @param customerId the value for public.customer.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.store_id
     *
     * @return the value of public.customer.store_id
     *
     * @mbg.generated
     */
    public Short getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.store_id
     *
     * @param storeId the value for public.customer.store_id
     *
     * @mbg.generated
     */
    public void setStoreId(Short storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.first_name
     *
     * @return the value of public.customer.first_name
     *
     * @mbg.generated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.first_name
     *
     * @param firstName the value for public.customer.first_name
     *
     * @mbg.generated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.last_name
     *
     * @return the value of public.customer.last_name
     *
     * @mbg.generated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.last_name
     *
     * @param lastName the value for public.customer.last_name
     *
     * @mbg.generated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.email
     *
     * @return the value of public.customer.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.email
     *
     * @param email the value for public.customer.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.address_id
     *
     * @return the value of public.customer.address_id
     *
     * @mbg.generated
     */
    public Short getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.address_id
     *
     * @param addressId the value for public.customer.address_id
     *
     * @mbg.generated
     */
    public void setAddressId(Short addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.activebool
     *
     * @return the value of public.customer.activebool
     *
     * @mbg.generated
     */
    public Boolean getActivebool() {
        return activebool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.activebool
     *
     * @param activebool the value for public.customer.activebool
     *
     * @mbg.generated
     */
    public void setActivebool(Boolean activebool) {
        this.activebool = activebool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.create_date
     *
     * @return the value of public.customer.create_date
     *
     * @mbg.generated
     */
    public LocalDate getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.create_date
     *
     * @param createDate the value for public.customer.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(LocalDate createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.last_update
     *
     * @return the value of public.customer.last_update
     *
     * @mbg.generated
     */
    public LocalDateTime getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.last_update
     *
     * @param lastUpdate the value for public.customer.last_update
     *
     * @mbg.generated
     */
    public void setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.active
     *
     * @return the value of public.customer.active
     *
     * @mbg.generated
     */
    public Integer getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.active
     *
     * @param active the value for public.customer.active
     *
     * @mbg.generated
     */
    public void setActive(Integer active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.customer
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Customer other = (Customer) that;
        return (this.getCustomerId() == null ? other.getCustomerId() == null : this.getCustomerId().equals(other.getCustomerId()))
            && (this.getStoreId() == null ? other.getStoreId() == null : this.getStoreId().equals(other.getStoreId()))
            && (this.getFirstName() == null ? other.getFirstName() == null : this.getFirstName().equals(other.getFirstName()))
            && (this.getLastName() == null ? other.getLastName() == null : this.getLastName().equals(other.getLastName()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getAddressId() == null ? other.getAddressId() == null : this.getAddressId().equals(other.getAddressId()))
            && (this.getActivebool() == null ? other.getActivebool() == null : this.getActivebool().equals(other.getActivebool()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getLastUpdate() == null ? other.getLastUpdate() == null : this.getLastUpdate().equals(other.getLastUpdate()))
            && (this.getActive() == null ? other.getActive() == null : this.getActive().equals(other.getActive()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.customer
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCustomerId() == null) ? 0 : getCustomerId().hashCode());
        result = prime * result + ((getStoreId() == null) ? 0 : getStoreId().hashCode());
        result = prime * result + ((getFirstName() == null) ? 0 : getFirstName().hashCode());
        result = prime * result + ((getLastName() == null) ? 0 : getLastName().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getAddressId() == null) ? 0 : getAddressId().hashCode());
        result = prime * result + ((getActivebool() == null) ? 0 : getActivebool().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getLastUpdate() == null) ? 0 : getLastUpdate().hashCode());
        result = prime * result + ((getActive() == null) ? 0 : getActive().hashCode());
        return result;
    }
}