package mybatis.model;

import java.time.LocalDateTime;

public class FilmActor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.film_actor.actor_id
     *
     * @mbg.generated
     */
    private Short actorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.film_actor.film_id
     *
     * @mbg.generated
     */
    private Short filmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.film_actor.last_update
     *
     * @mbg.generated
     */
    private LocalDateTime lastUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.film_actor.actor_id
     *
     * @return the value of public.film_actor.actor_id
     *
     * @mbg.generated
     */
    public Short getActorId() {
        return actorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.film_actor.actor_id
     *
     * @param actorId the value for public.film_actor.actor_id
     *
     * @mbg.generated
     */
    public void setActorId(Short actorId) {
        this.actorId = actorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.film_actor.film_id
     *
     * @return the value of public.film_actor.film_id
     *
     * @mbg.generated
     */
    public Short getFilmId() {
        return filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.film_actor.film_id
     *
     * @param filmId the value for public.film_actor.film_id
     *
     * @mbg.generated
     */
    public void setFilmId(Short filmId) {
        this.filmId = filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.film_actor.last_update
     *
     * @return the value of public.film_actor.last_update
     *
     * @mbg.generated
     */
    public LocalDateTime getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.film_actor.last_update
     *
     * @param lastUpdate the value for public.film_actor.last_update
     *
     * @mbg.generated
     */
    public void setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film_actor
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FilmActor other = (FilmActor) that;
        return (this.getActorId() == null ? other.getActorId() == null : this.getActorId().equals(other.getActorId()))
            && (this.getFilmId() == null ? other.getFilmId() == null : this.getFilmId().equals(other.getFilmId()))
            && (this.getLastUpdate() == null ? other.getLastUpdate() == null : this.getLastUpdate().equals(other.getLastUpdate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.film_actor
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getActorId() == null) ? 0 : getActorId().hashCode());
        result = prime * result + ((getFilmId() == null) ? 0 : getFilmId().hashCode());
        result = prime * result + ((getLastUpdate() == null) ? 0 : getLastUpdate().hashCode());
        return result;
    }
}