package mybatis.model;

import java.time.LocalDateTime;

public class Inventory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inventory.inventory_id
     *
     * @mbg.generated
     */
    private Integer inventoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inventory.film_id
     *
     * @mbg.generated
     */
    private Short filmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inventory.store_id
     *
     * @mbg.generated
     */
    private Short storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.inventory.last_update
     *
     * @mbg.generated
     */
    private LocalDateTime lastUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inventory.inventory_id
     *
     * @return the value of public.inventory.inventory_id
     *
     * @mbg.generated
     */
    public Integer getInventoryId() {
        return inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inventory.inventory_id
     *
     * @param inventoryId the value for public.inventory.inventory_id
     *
     * @mbg.generated
     */
    public void setInventoryId(Integer inventoryId) {
        this.inventoryId = inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inventory.film_id
     *
     * @return the value of public.inventory.film_id
     *
     * @mbg.generated
     */
    public Short getFilmId() {
        return filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inventory.film_id
     *
     * @param filmId the value for public.inventory.film_id
     *
     * @mbg.generated
     */
    public void setFilmId(Short filmId) {
        this.filmId = filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inventory.store_id
     *
     * @return the value of public.inventory.store_id
     *
     * @mbg.generated
     */
    public Short getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inventory.store_id
     *
     * @param storeId the value for public.inventory.store_id
     *
     * @mbg.generated
     */
    public void setStoreId(Short storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.inventory.last_update
     *
     * @return the value of public.inventory.last_update
     *
     * @mbg.generated
     */
    public LocalDateTime getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.inventory.last_update
     *
     * @param lastUpdate the value for public.inventory.last_update
     *
     * @mbg.generated
     */
    public void setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inventory
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Inventory other = (Inventory) that;
        return (this.getInventoryId() == null ? other.getInventoryId() == null : this.getInventoryId().equals(other.getInventoryId()))
            && (this.getFilmId() == null ? other.getFilmId() == null : this.getFilmId().equals(other.getFilmId()))
            && (this.getStoreId() == null ? other.getStoreId() == null : this.getStoreId().equals(other.getStoreId()))
            && (this.getLastUpdate() == null ? other.getLastUpdate() == null : this.getLastUpdate().equals(other.getLastUpdate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.inventory
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getInventoryId() == null) ? 0 : getInventoryId().hashCode());
        result = prime * result + ((getFilmId() == null) ? 0 : getFilmId().hashCode());
        result = prime * result + ((getStoreId() == null) ? 0 : getStoreId().hashCode());
        result = prime * result + ((getLastUpdate() == null) ? 0 : getLastUpdate().hashCode());
        return result;
    }
}