package mybatis.model;

import java.time.LocalDateTime;

public class Language {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.language.language_id
     *
     * @mbg.generated
     */
    private Integer languageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.language.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.language.last_update
     *
     * @mbg.generated
     */
    private LocalDateTime lastUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.language.language_id
     *
     * @return the value of public.language.language_id
     *
     * @mbg.generated
     */
    public Integer getLanguageId() {
        return languageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.language.language_id
     *
     * @param languageId the value for public.language.language_id
     *
     * @mbg.generated
     */
    public void setLanguageId(Integer languageId) {
        this.languageId = languageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.language.name
     *
     * @return the value of public.language.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.language.name
     *
     * @param name the value for public.language.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.language.last_update
     *
     * @return the value of public.language.last_update
     *
     * @mbg.generated
     */
    public LocalDateTime getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.language.last_update
     *
     * @param lastUpdate the value for public.language.last_update
     *
     * @mbg.generated
     */
    public void setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.language
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Language other = (Language) that;
        return (this.getLanguageId() == null ? other.getLanguageId() == null : this.getLanguageId().equals(other.getLanguageId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getLastUpdate() == null ? other.getLastUpdate() == null : this.getLastUpdate().equals(other.getLastUpdate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.language
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLanguageId() == null) ? 0 : getLanguageId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getLastUpdate() == null) ? 0 : getLastUpdate().hashCode());
        return result;
    }
}