package mybatis.model;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class Payment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.payment.payment_id
     *
     * @mbg.generated
     */
    private Integer paymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.payment.customer_id
     *
     * @mbg.generated
     */
    private Short customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.payment.staff_id
     *
     * @mbg.generated
     */
    private Short staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.payment.rental_id
     *
     * @mbg.generated
     */
    private Integer rentalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.payment.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.payment.payment_date
     *
     * @mbg.generated
     */
    private LocalDateTime paymentDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.payment.payment_id
     *
     * @return the value of public.payment.payment_id
     *
     * @mbg.generated
     */
    public Integer getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.payment.payment_id
     *
     * @param paymentId the value for public.payment.payment_id
     *
     * @mbg.generated
     */
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.payment.customer_id
     *
     * @return the value of public.payment.customer_id
     *
     * @mbg.generated
     */
    public Short getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.payment.customer_id
     *
     * @param customerId the value for public.payment.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Short customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.payment.staff_id
     *
     * @return the value of public.payment.staff_id
     *
     * @mbg.generated
     */
    public Short getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.payment.staff_id
     *
     * @param staffId the value for public.payment.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(Short staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.payment.rental_id
     *
     * @return the value of public.payment.rental_id
     *
     * @mbg.generated
     */
    public Integer getRentalId() {
        return rentalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.payment.rental_id
     *
     * @param rentalId the value for public.payment.rental_id
     *
     * @mbg.generated
     */
    public void setRentalId(Integer rentalId) {
        this.rentalId = rentalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.payment.amount
     *
     * @return the value of public.payment.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.payment.amount
     *
     * @param amount the value for public.payment.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.payment.payment_date
     *
     * @return the value of public.payment.payment_date
     *
     * @mbg.generated
     */
    public LocalDateTime getPaymentDate() {
        return paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.payment.payment_date
     *
     * @param paymentDate the value for public.payment.payment_date
     *
     * @mbg.generated
     */
    public void setPaymentDate(LocalDateTime paymentDate) {
        this.paymentDate = paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Payment other = (Payment) that;
        return (this.getPaymentId() == null ? other.getPaymentId() == null : this.getPaymentId().equals(other.getPaymentId()))
            && (this.getCustomerId() == null ? other.getCustomerId() == null : this.getCustomerId().equals(other.getCustomerId()))
            && (this.getStaffId() == null ? other.getStaffId() == null : this.getStaffId().equals(other.getStaffId()))
            && (this.getRentalId() == null ? other.getRentalId() == null : this.getRentalId().equals(other.getRentalId()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getPaymentDate() == null ? other.getPaymentDate() == null : this.getPaymentDate().equals(other.getPaymentDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPaymentId() == null) ? 0 : getPaymentId().hashCode());
        result = prime * result + ((getCustomerId() == null) ? 0 : getCustomerId().hashCode());
        result = prime * result + ((getStaffId() == null) ? 0 : getStaffId().hashCode());
        result = prime * result + ((getRentalId() == null) ? 0 : getRentalId().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getPaymentDate() == null) ? 0 : getPaymentDate().hashCode());
        return result;
    }
}