package mybatis.model;

import java.time.LocalDateTime;

public class Rental {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rental.rental_id
     *
     * @mbg.generated
     */
    private Integer rentalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rental.rental_date
     *
     * @mbg.generated
     */
    private LocalDateTime rentalDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rental.inventory_id
     *
     * @mbg.generated
     */
    private Integer inventoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rental.customer_id
     *
     * @mbg.generated
     */
    private Short customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rental.return_date
     *
     * @mbg.generated
     */
    private LocalDateTime returnDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rental.staff_id
     *
     * @mbg.generated
     */
    private Short staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rental.last_update
     *
     * @mbg.generated
     */
    private LocalDateTime lastUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rental.rental_id
     *
     * @return the value of public.rental.rental_id
     *
     * @mbg.generated
     */
    public Integer getRentalId() {
        return rentalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rental.rental_id
     *
     * @param rentalId the value for public.rental.rental_id
     *
     * @mbg.generated
     */
    public void setRentalId(Integer rentalId) {
        this.rentalId = rentalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rental.rental_date
     *
     * @return the value of public.rental.rental_date
     *
     * @mbg.generated
     */
    public LocalDateTime getRentalDate() {
        return rentalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rental.rental_date
     *
     * @param rentalDate the value for public.rental.rental_date
     *
     * @mbg.generated
     */
    public void setRentalDate(LocalDateTime rentalDate) {
        this.rentalDate = rentalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rental.inventory_id
     *
     * @return the value of public.rental.inventory_id
     *
     * @mbg.generated
     */
    public Integer getInventoryId() {
        return inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rental.inventory_id
     *
     * @param inventoryId the value for public.rental.inventory_id
     *
     * @mbg.generated
     */
    public void setInventoryId(Integer inventoryId) {
        this.inventoryId = inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rental.customer_id
     *
     * @return the value of public.rental.customer_id
     *
     * @mbg.generated
     */
    public Short getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rental.customer_id
     *
     * @param customerId the value for public.rental.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Short customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rental.return_date
     *
     * @return the value of public.rental.return_date
     *
     * @mbg.generated
     */
    public LocalDateTime getReturnDate() {
        return returnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rental.return_date
     *
     * @param returnDate the value for public.rental.return_date
     *
     * @mbg.generated
     */
    public void setReturnDate(LocalDateTime returnDate) {
        this.returnDate = returnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rental.staff_id
     *
     * @return the value of public.rental.staff_id
     *
     * @mbg.generated
     */
    public Short getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rental.staff_id
     *
     * @param staffId the value for public.rental.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(Short staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rental.last_update
     *
     * @return the value of public.rental.last_update
     *
     * @mbg.generated
     */
    public LocalDateTime getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rental.last_update
     *
     * @param lastUpdate the value for public.rental.last_update
     *
     * @mbg.generated
     */
    public void setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rental
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Rental other = (Rental) that;
        return (this.getRentalId() == null ? other.getRentalId() == null : this.getRentalId().equals(other.getRentalId()))
            && (this.getRentalDate() == null ? other.getRentalDate() == null : this.getRentalDate().equals(other.getRentalDate()))
            && (this.getInventoryId() == null ? other.getInventoryId() == null : this.getInventoryId().equals(other.getInventoryId()))
            && (this.getCustomerId() == null ? other.getCustomerId() == null : this.getCustomerId().equals(other.getCustomerId()))
            && (this.getReturnDate() == null ? other.getReturnDate() == null : this.getReturnDate().equals(other.getReturnDate()))
            && (this.getStaffId() == null ? other.getStaffId() == null : this.getStaffId().equals(other.getStaffId()))
            && (this.getLastUpdate() == null ? other.getLastUpdate() == null : this.getLastUpdate().equals(other.getLastUpdate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rental
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRentalId() == null) ? 0 : getRentalId().hashCode());
        result = prime * result + ((getRentalDate() == null) ? 0 : getRentalDate().hashCode());
        result = prime * result + ((getInventoryId() == null) ? 0 : getInventoryId().hashCode());
        result = prime * result + ((getCustomerId() == null) ? 0 : getCustomerId().hashCode());
        result = prime * result + ((getReturnDate() == null) ? 0 : getReturnDate().hashCode());
        result = prime * result + ((getStaffId() == null) ? 0 : getStaffId().hashCode());
        result = prime * result + ((getLastUpdate() == null) ? 0 : getLastUpdate().hashCode());
        return result;
    }
}