package mybatis.model;

import java.time.LocalDateTime;

public class Store {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.store.store_id
     *
     * @mbg.generated
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.store.manager_staff_id
     *
     * @mbg.generated
     */
    private Short managerStaffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.store.address_id
     *
     * @mbg.generated
     */
    private Short addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.store.last_update
     *
     * @mbg.generated
     */
    private LocalDateTime lastUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.store.store_id
     *
     * @return the value of public.store.store_id
     *
     * @mbg.generated
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.store.store_id
     *
     * @param storeId the value for public.store.store_id
     *
     * @mbg.generated
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.store.manager_staff_id
     *
     * @return the value of public.store.manager_staff_id
     *
     * @mbg.generated
     */
    public Short getManagerStaffId() {
        return managerStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.store.manager_staff_id
     *
     * @param managerStaffId the value for public.store.manager_staff_id
     *
     * @mbg.generated
     */
    public void setManagerStaffId(Short managerStaffId) {
        this.managerStaffId = managerStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.store.address_id
     *
     * @return the value of public.store.address_id
     *
     * @mbg.generated
     */
    public Short getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.store.address_id
     *
     * @param addressId the value for public.store.address_id
     *
     * @mbg.generated
     */
    public void setAddressId(Short addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.store.last_update
     *
     * @return the value of public.store.last_update
     *
     * @mbg.generated
     */
    public LocalDateTime getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.store.last_update
     *
     * @param lastUpdate the value for public.store.last_update
     *
     * @mbg.generated
     */
    public void setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.store
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Store other = (Store) that;
        return (this.getStoreId() == null ? other.getStoreId() == null : this.getStoreId().equals(other.getStoreId()))
            && (this.getManagerStaffId() == null ? other.getManagerStaffId() == null : this.getManagerStaffId().equals(other.getManagerStaffId()))
            && (this.getAddressId() == null ? other.getAddressId() == null : this.getAddressId().equals(other.getAddressId()))
            && (this.getLastUpdate() == null ? other.getLastUpdate() == null : this.getLastUpdate().equals(other.getLastUpdate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.store
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getStoreId() == null) ? 0 : getStoreId().hashCode());
        result = prime * result + ((getManagerStaffId() == null) ? 0 : getManagerStaffId().hashCode());
        result = prime * result + ((getAddressId() == null) ? 0 : getAddressId().hashCode());
        result = prime * result + ((getLastUpdate() == null) ? 0 : getLastUpdate().hashCode());
        return result;
    }
}